###
POST http://localhost:8080/api/question
Content-Type: application/json

{
  "surveyId": 1,
  "prompt": "True or False: I is a vowel?",
  "answer": "True"
}

###
GET http://localhost:8080/api/question?surveyId=1