###
POST http://localhost:8080/api/question
Content-Type: application/json

{
  "surveyId": 4,
  "prompt": "True or False: F is a vowel?",
  "answer": "False"
}

###
GET http://localhost:8080/api/question?surveyId=1