###
POST http://localhost:8080/api/survey
Content-Type: application/json

{
  "id": 1,
  "title": "testing"
}

###
GET http://localhost:8080/api/survey?surveyId=1668713318319

###
GET http://localhost:8080/api/survey/all-survey

###
DELETE http://localhost:8080/api/survey?surveyId=24

###
PUT http://localhost:8080/api/survey
Content-Type: application/json

{
  "id": 20,
  "title": "vowels"
}